addSquad: SUCCESS
addSquad: SUCCESS
addSquad: SUCCESS
addSquad: SUCCESS
addSquad: SUCCESS
addSquad: SUCCESS
addSquad: SUCCESS
addSquad: SUCCESS
addSquad: SUCCESS
addSquad: SUCCESS
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: SUCCESS
removeSquad: SUCCESS
squadDuel: FAILURE
addHunter: SUCCESS
forceJoin: FAILURE
