addSquad: SUCCESS
addSquad: SUCCESS
addSquad: SUCCESS
addSquad: SUCCESS
addSquad: SUCCESS
addSquad: SUCCESS
addSquad: SUCCESS
addSquad: SUCCESS
addSquad: SUCCESS
addSquad: SUCCESS
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: FAILURE
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: FAILURE
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: FAILURE
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: FAILURE
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: SUCCESS
addHunter: SUCCESS
removeSquad: FAILURE
forceJoin: FAILURE
getPartialNenAbility: INVALID_INPUT
squadDuel: FAILURE
getPartialNenAbility: INVALID_INPUT
squadDuel: FAILURE
removeSquad: SUCCESS
addHunter: SUCCESS
forceJoin: FAILURE
getIthCollectiveAuraSquad: SUCCESS, 10
removeSquad: SUCCESS
squadDuel: FAILURE
getIthCollectiveAuraSquad: SUCCESS, 3
removeSquad: INVALID_INPUT
getIthCollectiveAuraSquad: SUCCESS, 1
removeSquad: SUCCESS
forceJoin: FAILURE
removeSquad: SUCCESS
forceJoin: FAILURE
addSquad: SUCCESS
addHunter: FAILURE
getPartialNenAbility: FAILURE
addSquad: SUCCESS
removeSquad: FAILURE
squadDuel: FAILURE
removeSquad: SUCCESS
forceJoin: INVALID_INPUT
forceJoin: FAILURE
forceJoin: FAILURE
forceJoin: FAILURE
addSquad: SUCCESS
removeSquad: FAILURE
addHunter: SUCCESS
squadDuel: FAILURE
getIthCollectiveAuraSquad: SUCCESS, 8
getIthCollectiveAuraSquad: SUCCESS, 5
addSquad: SUCCESS
getIthCollectiveAuraSquad: FAILURE
removeSquad: FAILURE
